import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";


const ProfilePage: NextPage = () => {

  const { data, isLoading } = api.profile.getUserByUserName.useQuery({
    username: 'jjxrry',
  })

  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>404</div>

  return (
    <>
      <Head>
        <title>Profile Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>
          {`@${data.username}`}
        </div>
      </main>
    </>
  )
}

export default ProfilePage